import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:kresai/models/exam.dart';
import 'package:kresai/config/exam_config.dart';
import 'package:kresai/services/exam_ai_service.dart';
import 'package:kresai/services/exam_store.dart';
import 'package:kresai/services/registration_store.dart';
import 'package:kresai/theme/tokens.dart';

/// Exam Creation Screen - Teacher generates exams with AI
class ExamCreationScreen extends StatefulWidget {
  const ExamCreationScreen({super.key});

  @override
  State<ExamCreationScreen> createState() => _ExamCreationScreenState();
}

class _ExamCreationScreenState extends State<ExamCreationScreen> {
  final _topicsController = TextEditingController();
  final _aiService = ExamAIService();
  final _examStore = ExamStore();
  final _registrationStore = RegistrationStore();
  final String? _currentTeacherId = FirebaseAuth.instance.currentUser?.uid;

  // Form state
  String _selectedGrade = 'anaokulu';
  String _selectedTimeWindow = 'gunluk';
  String _selectedDifficulty = 'orta';
  String _selectedTeacherStyle = 'oyunlaştırılmış';
  int _questionCount = 10;
  int _durationMinutes = 10;
  List<String> _selectedFormats = ['mcq', 'trueFalse', 'pictureChoice'];

  // Generation state
  bool _isLoading = false;
  bool _isGenerating = false;
  List<ExamVersion>? _generatedVersions;
  String? _summaryForTeacher;
  int? _selectedVersionIndex;

  String? _classContext;

  @override
  void initState() {
    super.initState();
    _loadClassContext();
  }

  Future<void> _loadClassContext() async {
    await _registrationStore.load();
    final teacherReg = _registrationStore.getCurrentTeacherRegistration();
    if (teacherReg != null && mounted) {
      setState(() {
        _classContext = '${teacherReg.className}, ${teacherReg.classSize} öğrenci';
      });
    }
  }

  Future<void> _generateExam() async {
    if (_topicsController.text.trim().isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Lütfen konu girin')),
      );
      return;
    }

    if (_selectedFormats.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('En az bir soru formatı seçin')),
      );
      return;
    }

    setState(() {
      _isGenerating = true;
      _generatedVersions = null;
      _selectedVersionIndex = null;
    });

    try {
      final result = await _aiService.generateExam(
        gradeBand: _selectedGrade,
        timeWindow: _selectedTimeWindow,
        topics: _topicsController.text.split(',').map((e) => e.trim()).toList(),
        questionCount: _questionCount,
        durationMinutes: _durationMinutes,
        difficulty: _selectedDifficulty,
        teacherStyle: _selectedTeacherStyle,
        formatsAllowed: _selectedFormats,
      );

      if (mounted) {
        setState(() {
          _generatedVersions = result.versions;
          _summaryForTeacher = result.summaryForTeacher;
          _isGenerating = false;
        });
      }
    } catch (e) {
      if (mounted) {
        setState(() => _isGenerating = false);
        // User-friendly error dialog
        showDialog(
          context: context,
          builder: (ctx) => AlertDialog(
            title: const Text('Üzgünüz 😔'),
            content: Text(
              e.toString().contains('429') || e.toString().contains('Quota')
                  ? 'Servis şu an çok yoğun. Lütfen 1 dakika sonra tekrar deneyin. (Quota Exceeded)'
                  : 'Bir hata oluştu: $e',
            ),
            actions: [
              TextButton(
                onPressed: () => Navigator.pop(ctx),
                child: const Text('Tamam'),
              ),
            ],
          ),
        );
      }
    }
  }

  Future<void> _publishExam() async {
    if (_selectedVersionIndex == null || _generatedVersions == null || _currentTeacherId == null) {
      return;
    }

    final selectedVersion = _generatedVersions![_selectedVersionIndex!];

    // Show confirmation dialog with due date picker
    final dueDate = await _showPublishDialog();
    if (dueDate == null) return;

    setState(() => _isLoading = true);

    try {
      final now = DateTime.now();
      
      // Extract answer key from teacher notes
      final teacherNotes = selectedVersion.teacherNotes;
      final answerKey = ExamAnswerKey(
        correctAnswers: Map<String, dynamic>.from(teacherNotes['answerKey'] ?? {}),
        explanations: Map<String, String>.from(teacherNotes['explanations'] ?? {}),
        commonMistakes: (teacherNotes['commonMistakes'] as Map<String, dynamic>?)
            ?.map((k, v) => MapEntry(k, (v as List).cast<String>())) ?? {},
      );

      final exam = Exam(
        id: '', // Will be generated by Firestore
        teacherId: _currentTeacherId!,
        classId: _classContext ?? 'default_class',
        schoolId: 'default_school',
        gradeBand: _selectedGrade,
        timeWindow: _selectedTimeWindow,
        topics: _topicsController.text.split(',').map((e) => e.trim()).toList(),
        teacherStyle: _selectedTeacherStyle,
        status: ExamStatus.draft, // Start as draft
        targetStudentIds: [], // Empty = entire class
        title: selectedVersion.title,
        questions: selectedVersion.questions,
        estimatedMinutes: selectedVersion.estimatedMinutes,
        maxScore: selectedVersion.questions.fold(0, (sum, q) => sum + q.points),
        instructions: selectedVersion.instructions,
        answerKey: answerKey,
        commonMisconceptions: List<String>.from(teacherNotes['commonMisconceptions'] ?? []),
        createdAt: now,
        updatedAt: now,
      );

      // Create draft then publish
      final examId = await _examStore.createDraftExam(exam);
      await _examStore.publishExam(examId: examId, dueDate: dueDate);

      if (mounted) {
        setState(() => _isLoading = false);
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('✅ Sınav yayınlandı!'),
            backgroundColor: Colors.green,
          ),
        );
        Navigator.pop(context); // Return to management screen
      }
    } catch (e) {
      if (mounted) {
        setState(() => _isLoading = false);
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Hata: $e'),
            backgroundColor: AppTokens.errorLight,
          ),
        );
      }
    }
  }

  Future<DateTime?> _showPublishDialog() async {
    DateTime selectedDate = DateTime.now().add(const Duration(days: 3));
    
    return showDialog<DateTime>(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Sınavı Yayınla'),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            const Text('Son teslim tarihi:'),
            const SizedBox(height: 16),
            StatefulBuilder(
              builder: (context, setDialogState) => InkWell(
                onTap: () async {
                  final picked = await showDatePicker(
                    context: context,
                    initialDate: selectedDate,
                    firstDate: DateTime.now(),
                    lastDate: DateTime.now().add(const Duration(days: 30)),
                  );
                  if (picked != null) {
                    setDialogState(() => selectedDate = picked);
                  }
                },
                child: InputDecorator(
                  decoration: const InputDecoration(
                    labelText: 'Tarih Seç',
                    border: OutlineInputBorder(),
                    prefixIcon: Icon(Icons.calendar_today),
                  ),
                  child: Text(
                    '${selectedDate.day}/${selectedDate.month}/${selectedDate.year}',
                  ),
                ),
              ),
            ),
          ],
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text('İptal'),
          ),
          ElevatedButton(
            onPressed: () => Navigator.pop(context, selectedDate),
            child: const Text('Yayınla'),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Yeni Sınav Oluştur'),
        bottom: _isGenerating
            ? const PreferredSize(
                preferredSize: Size.fromHeight(4.0),
                child: LinearProgressIndicator(),
              )
            : null,
      ),
      body: ListView(
        padding: const EdgeInsets.all(AppTokens.spacing16),
        children: [
          // Input Form
          _buildInputForm(),
          
          const SizedBox(height: AppTokens.spacing24),
          
          // Generate Button
          SizedBox(
            width: double.infinity,
            child: ElevatedButton.icon(
              onPressed: _isGenerating ? null : _generateExam,
              icon: _isGenerating
                  ? const SizedBox(
                      width: 20,
                      height: 20,
                      child: CircularProgressIndicator(strokeWidth: 2),
                    )
                  : const Icon(Icons.auto_awesome),
              label: Text(_isGenerating ? 'Üretiliyor...' : 'AI ile Sınav Üret'),
              style: ElevatedButton.styleFrom(
                backgroundColor: AppTokens.primaryLight,
                foregroundColor: Colors.white,
                padding: const EdgeInsets.symmetric(vertical: 16),
              ),
            ),
          ),
          
          const SizedBox(height: AppTokens.spacing24),
          
          // Generated Versions
          if (_generatedVersions != null) ...[ 
            Text(
              'Sınav Versiyonları (${_generatedVersions!.length})',
              style: const TextStyle(
                fontSize: 18,
                fontWeight: FontWeight.bold,
              ),
            ),
            const SizedBox(height: AppTokens.spacing8),
            
            if (_summaryForTeacher != null)
              Card(
                color: AppTokens.primaryLight.withOpacity(0.1),
                child: Padding(
                  padding: const EdgeInsets.all(AppTokens.spacing12),
                  child: Row(
                    children: [
                      Icon(Icons.lightbulb, color: AppTokens.primaryLight),
                      const SizedBox(width: 8),
                      Expanded(
                        child: Text(
                          _summaryForTeacher!,
                          style: const TextStyle(fontSize: 13),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            
            const SizedBox(height: AppTokens.spacing16),
            
            ..._generatedVersions!.asMap().entries.map((entry) {
              final index = entry.key;
              final version = entry.value;
              return _buildVersionCard(index, version);
            }),
          ],
        ],
      ),
      floatingActionButton: _selectedVersionIndex != null
          ? FloatingActionButton.extended(
              onPressed: _isLoading ? null : _publishExam,
              icon: _isLoading
                  ? const SizedBox(
                      width: 20,
                      height: 20,
                      child: CircularProgressIndicator(strokeWidth: 2, color: Colors.white),
                    )
                  : const Icon(Icons.send),
              label: const Text('Yayınla'),
              backgroundColor: AppTokens.primaryLight,
            )
          : null,
    );
  }

  Widget _buildInputForm() {
    return Card(
      child: Padding(
        padding: const EdgeInsets.all(AppTokens.spacing16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Grade Band
            Text(
              'Düzey',
              style: TextStyle(
                fontWeight: FontWeight.w500,
                color: AppTokens.textSecondaryLight,
              ),
            ),
            const SizedBox(height: 8),
            Wrap(
              spacing: 8,
              children: ExamConfig.gradeBands.map((grade) {
                final isSelected = _selectedGrade == grade;
                return ChoiceChip(
                  label: Text(grade.toUpperCase()),
                  selected: isSelected,
                  onSelected: (selected) {
                    setState(() => _selectedGrade = grade);
                  },
                );
              }).toList(),
            ),
            
            const SizedBox(height: AppTokens.spacing16),
            
            // Topics
            TextField(
              controller: _topicsController,
              decoration: const InputDecoration(
                labelText: 'Konular (virgülle ayırın)',
                hintText: 'Örn: Renkler, Sayılar, Şekiller',
                border: OutlineInputBorder(),
                prefixIcon: Icon(Icons.topic),
              ),
              maxLines: 2,
            ),
            
            const SizedBox(height: AppTokens.spacing16),
            
            // Time Window
            Row(
              children: [
                Expanded(
                  child: DropdownButtonFormField<String>(
                    value: _selectedTimeWindow,
                    decoration: const InputDecoration(
                      labelText: 'Zaman',
                      border: OutlineInputBorder(),
                      prefixIcon: Icon(Icons.calendar_today),
                    ),
                    items: ExamConfig.timeWindows.map((t) {
                      return DropdownMenuItem(
                        value: t,
                        child: Text(t == 'gunluk' ? 'Günlük' : t == 'haftalik' ? 'Haftalık' : 'Dönemlik'),
                      );
                    }).toList(),
                    onChanged: (value) {
                      if (value != null) {
                        setState(() => _selectedTimeWindow = value);
                      }
                    },
                  ),
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: DropdownButtonFormField<String>(
                    value: _selectedDifficulty,
                    decoration: const InputDecoration(
                      labelText: 'Zorluk',
                      border: OutlineInputBorder(),
                      prefixIcon: Icon(Icons.trending_up),
                    ),
                    items: const [
                      DropdownMenuItem(value: 'kolay', child: Text('Kolay')),
                      DropdownMenuItem(value: 'orta', child: Text('Orta')),
                      DropdownMenuItem(value: 'zor', child: Text('Zor')),
                    ],
                    onChanged: (value) {
                      if (value != null) {
                        setState(() => _selectedDifficulty = value);
                      }
                    },
                  ),
                ),
              ],
            ),
            
            const SizedBox(height: AppTokens.spacing16),
            
            // Question Count & Duration
            Row(
              children: [
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        'Soru Sayısı: $_questionCount',
                        style: const TextStyle(fontWeight: FontWeight.w500),
                      ),
                      Slider(
                        value: _questionCount.toDouble(),
                        min: 5,
                        max: 20,
                        divisions: 15,
                        label: '$_questionCount',
                        onChanged: (value) {
                          setState(() => _questionCount = value.toInt());
                        },
                      ),
                    ],
                  ),
                ),
                const SizedBox(width: 16),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        'Süre: $_durationMinutes dk',
                        style: const TextStyle(fontWeight: FontWeight.w500),
                      ),
                      Slider(
                        value: _durationMinutes.toDouble(),
                        min: 5,
                        max: 60,
                        divisions: 11,
                        label: '$_durationMinutes dk',
                        onChanged: (value) {
                          setState(() => _durationMinutes = value.toInt());
                        },
                      ),
                    ],
                  ),
                ),
              ],
            ),
            
            const SizedBox(height: AppTokens.spacing16),
            
            // Teacher Style
            Text(
              'Öğretmen Stili',
              style: TextStyle(
                fontWeight: FontWeight.w500,
                color: AppTokens.textSecondaryLight,
              ),
            ),
            const SizedBox(height: 8),
            Wrap(
              spacing: 8,
              children: ExamConfig.teacherStyles.map((style) {
                final isSelected = _selectedTeacherStyle == style;
                return ChoiceChip(
                  label: Text(style == 'nazik' ? 'Nazik' : style == 'oyunlaştırılmış' ? 'Oyunlaştırılmış' : 'Klasik'),
                  selected: isSelected,
                  onSelected: (selected) {
                    setState(() => _selectedTeacherStyle = style);
                  },
                );
              }).toList(),
            ),
            
            const SizedBox(height: AppTokens.spacing16),
            
            // Question Formats
            Text(
              'Soru Formatları',
              style: TextStyle(
                fontWeight: FontWeight.w500,
                color: AppTokens.textSecondaryLight,
              ),
            ),
            const SizedBox(height: 8),
            Wrap(
              spacing: 8,
              runSpacing: 8,
              children: QuestionType.values.map((type) {
                final isSelected = _selectedFormats.contains(type.name);
                return FilterChip(
                  label: Text(type.label),
                  selected: isSelected,
                  onSelected: (selected) {
                    setState(() {
                      if (selected) {
                        _selectedFormats.add(type.name);
                      } else {
                        if (_selectedFormats.length > 1) {
                          _selectedFormats.remove(type.name);
                        }
                      }
                    });
                  },
                );
              }).toList(),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildVersionCard(int index, ExamVersion version) {
    final isSelected = _selectedVersionIndex == index;
    
    return Card(
      elevation: isSelected ? 4 : 1,
      color: isSelected ? AppTokens.primaryLight.withOpacity(0.1) : null,
      margin: const EdgeInsets.only(bottom: AppTokens.spacing16),
      child: Column(
        children: [
          ListTile(
            leading: CircleAvatar(
              backgroundColor: AppTokens.primaryLight,
              child: Text('V${index + 1}'),
            ),
            title: Text(
              version.title,
              style: const TextStyle(fontWeight: FontWeight.bold),
            ),
            subtitle: Text(
              '${version.questionCount} soru • ${version.estimatedMinutes} dk • ${version.formatMix.join(", ")}',
            ),
            trailing: isSelected
                ? Icon(Icons.check_circle, color: AppTokens.primaryLight)
                : Icon(Icons.circle_outlined, color: AppTokens.textSecondaryLight),
            onTap: () {
              setState(() {
                _selectedVersionIndex = isSelected ? null : index;
              });
            },
          ),
          
          // Expandable details
          if (isSelected) ...[
            const Divider(height: 1),
            Padding(
              padding: const EdgeInsets.all(AppTokens.spacing16),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    'Yönergeler',
                    style: TextStyle(
                      fontWeight: FontWeight.w500,
                      color: AppTokens.textSecondaryLight,
                    ),
                  ),
                  const SizedBox(height: 4),
                  ...version.instructions.asMap().entries.map((e) {
                    return Padding(
                      padding: const EdgeInsets.only(bottom: 4),
                      child: Text('${e.key + 1}. ${e.value}'),
                    );
                  }),
                  
                  const SizedBox(height: AppTokens.spacing12),
                  
                  Text(
                    'Sınav Soruları (${version.questions.length})',
                    style: const TextStyle(
                      fontWeight: FontWeight.w600,
                      fontSize: 16,
                    ),
                  ),
                  const SizedBox(height: 8),
                  
                  // Show ALL questions with details
                  ...version.questions.asMap().entries.map((entry) {
                    final qIndex = entry.key;
                    final q = entry.value;
                    
                    return Card(
                      margin: const EdgeInsets.only(bottom: 8),
                      color: Colors.grey[50],
                      child: Padding(
                        padding: const EdgeInsets.all(12),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            // Question number and prompt
                            Row(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Text(
                                  'S${qIndex + 1}.',
                                  style: const TextStyle(
                                    fontWeight: FontWeight.w600,
                                    fontSize: 14,
                                    color: Colors.blue,
                                  ),
                                ),
                                const SizedBox(width: 8),
                                Expanded(
                                  child: Text(
                                    q.prompt,
                                    style: const TextStyle(
                                      fontSize: 14,
                                    ),
                                  ),
                                ),
                              ],
                            ),
                            const SizedBox(height: 6),
                            
                            // Question metadata
                            Row(
                              children: [
                                Container(
                                  padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
                                  decoration: BoxDecoration(
                                    color: Colors.blue[100],
                                    borderRadius: BorderRadius.circular(12),
                                  ),
                                  child: Text(
                                    q.type.label,
                                    style: const TextStyle(fontSize: 11),
                                  ),
                                ),
                                const SizedBox(width: 8),
                                Text(
                                  '${q.points} puan',
                                  style: const TextStyle(
                                    fontSize: 12,
                                    color: Colors.grey,
                                  ),
                                ),
                                const Spacer(),
                                // Show correct answer badge
                                Container(
                                  padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
                                  decoration: BoxDecoration(
                                    color: Colors.green[50],
                                    borderRadius: BorderRadius.circular(12),
                                    border: Border.all(color: Colors.green.shade300),
                                  ),
                                  child: Text(
                                    '✓ ${q.correctAnswer}',
                                    style: TextStyle(
                                      fontSize: 11,
                                      color: Colors.green[800],
                                      fontWeight: FontWeight.w600,
                                    ),
                                  ),
                                ),
                              ],
                            ),
                            
                            // Show answer choices if available
                            if (q.choices != null && q.choices!.isNotEmpty) ...[
                              const SizedBox(height: 8),
                              const Divider(height: 1),
                              const SizedBox(height: 8),
                              
                              // For picture choice questions with images, show grid
                              if (q.type == QuestionType.pictureChoice && 
                                  q.choiceImageUrls != null && 
                                  q.choiceImageUrls!.isNotEmpty) ...[
                                GridView.builder(
                                  shrinkWrap: true,
                                  physics: const NeverScrollableScrollPhysics(),
                                  gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
                                    crossAxisCount: 2,
                                    crossAxisSpacing: 8,
                                    mainAxisSpacing: 8,
                                    childAspectRatio: 1.0,
                                  ),
                                  itemCount: q.choices!.length,
                                  itemBuilder: (context, choiceIndex) {
                                    final choice = q.choices![choiceIndex];
                                    final isCorrect = choice == q.correctAnswer;
                                    final letter = String.fromCharCode(65 + choiceIndex);
                                    final imageUrl = choiceIndex < q.choiceImageUrls!.length 
                                        ? q.choiceImageUrls![choiceIndex] 
                                        : null;
                                    
                                    return Card(
                                      elevation: isCorrect ? 3 : 1,
                                      color: isCorrect ? Colors.green[50] : Colors.white,
                                      shape: RoundedRectangleBorder(
                                        borderRadius: BorderRadius.circular(8),
                                        side: BorderSide(
                                          color: isCorrect ? Colors.green : Colors.grey.shade300,
                                          width: isCorrect ? 2 : 1,
                                        ),
                                      ),
                                      child: Column(
                                        mainAxisAlignment: MainAxisAlignment.center,
                                        children: [
                                          if (imageUrl != null)
                                            Expanded(
                                              child: ClipRRect(
                                                borderRadius: const BorderRadius.vertical(top: Radius.circular(8)),
                                                child: Image.network(
                                                  imageUrl,
                                                  fit: BoxFit.cover,
                                                  errorBuilder: (context, error, stackTrace) => 
                                                      Icon(Icons.broken_image, size: 40, color: Colors.grey[400]),
                                                ),
                                              ),
                                            ),
                                          Padding(
                                            padding: const EdgeInsets.all(8.0),
                                            child: Row(
                                              mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                              children: [
                                                Container(
                                                  width: 20,
                                                  height: 20,
                                                  decoration: BoxDecoration(
                                                    color: isCorrect ? Colors.green : Colors.grey[300],
                                                    shape: BoxShape.circle,
                                                  ),
                                                  child: Center(
                                                    child: Text(
                                                      letter,
                                                      style: TextStyle(
                                                        fontSize: 10,
                                                        fontWeight: FontWeight.bold,
                                                        color: isCorrect ? Colors.white : Colors.grey[700],
                                                      ),
                                                    ),
                                                  ),
                                                ),
                                                if (isCorrect)
                                                  Icon(Icons.check_circle, size: 20, color: Colors.green),
                                              ],
                                            ),
                                          ),
                                          Padding(
                                            padding: const EdgeInsets.fromLTRB(8, 0, 8, 8),
                                            child: Text(
                                              choice,
                                              style: TextStyle(
                                                fontSize: 11,
                                                fontWeight: isCorrect ? FontWeight.w600 : FontWeight.normal,
                                              ),
                                              textAlign: TextAlign.center,
                                              maxLines: 2,
                                              overflow: TextOverflow.ellipsis,
                                            ),
                                          ),
                                        ],
                                      ),
                                    );
                                  },
                                ),
                              ] else ...[
                                // Fallback to text-only display
                                ...q.choices!.asMap().entries.map((choiceEntry) {
                                  final choiceIndex = choiceEntry.key;
                                  final choice = choiceEntry.value;
                                  final isCorrect = choice == q.correctAnswer;
                                  final letter = String.fromCharCode(65 + choiceIndex); // A, B, C, D
                                  
                                  return Padding(
                                    padding: const EdgeInsets.only(bottom: 6),
                                    child: Row(
                                      children: [
                                        Container(
                                          width: 24,
                                          height: 24,
                                          decoration: BoxDecoration(
                                            color: isCorrect ? Colors.green[100] : Colors.grey[200],
                                            borderRadius: BorderRadius.circular(12),
                                            border: Border.all(
                                              color: isCorrect ? Colors.green : Colors.grey,
                                              width: isCorrect ? 2 : 1,
                                            ),
                                          ),
                                          child: Center(
                                            child: Text(
                                              letter,
                                              style: TextStyle(
                                                fontSize: 11,
                                                fontWeight: isCorrect ? FontWeight.bold : FontWeight.normal,
                                                color: isCorrect ? Colors.green[800] : Colors.grey[700],
                                              ),
                                            ),
                                          ),
                                        ),
                                        const SizedBox(width: 8),
                                        Expanded(
                                          child: Text(
                                            choice,
                                            style: TextStyle(
                                              fontSize: 13,
                                              fontWeight: isCorrect ? FontWeight.w600 : FontWeight.normal,
                                              color: isCorrect ? Colors.green[800] : Colors.grey[800],
                                            ),
                                          ),
                                        ),
                                        if (isCorrect)
                                          Icon(Icons.check_circle, size: 16, color: Colors.green[700]),
                                      ],
                                    ),
                                  );
                                }),
                              ],
                            ],
                          ],
                        ),
                      ),
                    );
                  }),
                  
                  const SizedBox(height: AppTokens.spacing12),
                  
                  Row(
                    children: [
                      Chip(
                        label: Text('Toplam: ${version.scoring['maxScore']} puan'),
                        backgroundColor: AppTokens.successLight.withOpacity(0.2),
                      ),
                      const SizedBox(width: 8),
                      if (version.scoring['autoGradable'] == true)
                        const Chip(
                          label: Text('Otomatik Puanlama'),
                          backgroundColor: Colors.blue,
                          labelStyle: TextStyle(color: Colors.white),
                        ),
                    ],
                  ),
                ],
              ),
            ),
          ],
        ],
      ),
    );
  }

  @override
  void dispose() {
    _topicsController.dispose();
    super.dispose();
  }
}
