workflows:
  default-workflow:
    name: Default Workflow
    instance_type: mac_mini_m2
    environment:
      # Code signing via scripts to handle certificate creation dynamically
      flutter: stable
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
        - pull_request
    integrations:
      app_store_connect: OkulAI
    scripts:
      - name: Initialize keychain
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          # Create certificates and profiles if they don't exist
          # Environment is clean, so this MUST create new ones.
          app-store-connect fetch-signing-files "com.ahmetkaya.okulai" --type IOS_APP_STORE --create
          keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Pre-build script
        script: |
          echo "$GOOGLE_SERVICE_INFO_PLIST" > $CM_BUILD_DIR/ios/Runner/GoogleService-Info.plist
      - name: Build iOS
        script: |
          flutter build ipa --release \
            --build-name=1.0.0 \
            --build-number=$(($BUILD_NUMBER + 100)) \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/Runner.app
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
