workflows:
  default-workflow:
    name: Default Workflow
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
        - pull_request
    scripts:
      - name: Pre-build script
        script: |
          # Create GoogleService-Info.plist from environment variable
          echo "$GOOGLE_SERVICE_INFO_PLIST" > $CM_BUILD_DIR/ios/Runner/GoogleService-Info.plist
          
          echo "Pre-build setup completed successfully"
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/Runner.app
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true
