workflows:
  default-workflow:
    name: Default Workflow
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
        - pull_request
    integrations:
      app_store_connect: OkulAI
    scripts:
      - name: Initialize keychain
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          # Fetch provisioning profiles and certificates
          # Creates them if they don't exist
          app-store-connect fetch-signing-files "com.ahmetkaya.okulai" --type IOS_APP_STORE --create
      - name: Add certificates to keychain
        script: |
          keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Pre-build script
        script: |
          # Create GoogleService-Info.plist from environment variable
          echo "$GOOGLE_SERVICE_INFO_PLIST" > $CM_BUILD_DIR/ios/Runner/GoogleService-Info.plist
          
          echo "Pre-build setup completed successfully"
      - name: Build iOS
        script: |
          # Build IPA for distribution
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/Runner.app
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
