// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD82IvYsou_AXNTSNBRCAWCCIEmGEJhAk',
    appId: '1:117649531642:web:e9832ca5df0182c06ddf43',
    messagingSenderId: '117649531642',
    projectId: 'okulai-dev',
    authDomain: 'okulai-dev.firebaseapp.com',
    storageBucket: 'okulai-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_EvYSRzTk1Yvfjyxgla-qc-9vtS5mVU4',
    appId: '1:140244239573:android:a79e5ccf7d43a8dfb48e5c',
    messagingSenderId: '140244239573',
    projectId: 'okulavatar',
    storageBucket: 'okulavatar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_EvYSRzTk1Yvfjyxgla-qc-9vtS5mVU4',
    appId: '1:140244239573:ios:ios_app_id_here',
    messagingSenderId: '140244239573',
    projectId: 'okulavatar',
    storageBucket: 'okulavatar.firebasestorage.app',
    iosBundleId: 'com.example.kresai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_EvYSRzTk1Yvfjyxgla-qc-9vtS5mVU4',
    appId: '1:140244239573:macos:macos_app_id_here',
    messagingSenderId: '140244239573',
    projectId: 'okulavatar',
    storageBucket: 'okulavatar.firebasestorage.app',
    iosBundleId: 'com.example.kresai',
  );
}