platform :ios, '13.0'

# CocoaPods analytics sends network stats. If you want to disable this, uncomment the following line.
# disable_cocoapods_analytics!

install! 'cocoapods', :deterministic_uuids => false

target 'Runner' do
  use_frameworks!
  use_flutter_install_all_ios_pods File.expand_path(File.join('..', '..', 'flutter', '.ios', 'Flutter', 'podhelper.rb'), __FILE__)
  
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
